// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test3', async function() {
    await driver.get("https://bstackdemo.com/")
    await driver.manage().window().setRect({ width: 1050, height: 724 })
    await driver.findElement(By.id("signin")).click()
    await driver.findElement(By.id("react-select-2-input")).sendKeys("random")
    await driver.findElement(By.id("react-select-2-input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".css-1wa3eu0-placeholder")).click()
    await driver.findElement(By.id("__next")).click()
    await driver.findElement(By.css(".css-1wa3eu0-placeholder")).click()
    await driver.findElement(By.id("react-select-3-input")).sendKeys("random2")
    await driver.findElement(By.id("react-select-3-input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("login-btn")).click()
    await driver.findElement(By.id("react-select-2-option-0-0")).click()
    await driver.findElement(By.css(".Modal_modal__3I0HK")).click()
    await driver.findElement(By.id("login-btn")).click()
  })
})
